### ISSUE TITLE
To Do List?

### ISSUE THREAD

**Issue by acreilly** [skukx/avatax#1]
Could you create a to do list? I don't want to step on each others toes.

**Comment by skukx** [comment]
@acreilly I'll start working on one today.  The first thing I want to do is improve specs and docs.  The transactions api is the only code implemented currently in the gem (Which is enough for spree/solidus).  Do you want me to create an issue for each step?

**Comment by acreilly** [comment]
Are you at the conference? Would love to work on this together. I began integrating this gem into solidus_avatax_certified and it is looking good so far

**Comment by skukx** [comment]
@acreilly Yeah, I'm in the very front. I look like this:
![bitmoji](https://render.bitstrips.com/v2/cpanel/9941941-228647270_8-s1-v1.png?transparent=1&palette=1&width=246)
